const cfg=window.CLEAR_LANKA_SUPABASE;
const client=window.supabase?.createClient(cfg?.url,cfg?.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const login=document.querySelector('#login-view'),app=document.querySelector('#admin-app'),toast=document.querySelector('.toast'),loginStatus=document.querySelector('.login-status');
const defaults={heroEyebrow:'Local help. Honest answers.',heroTitle:'Sri Lanka travel, made clear.',heroLead:'Plan your Sri Lanka trip with verified local drivers and guides, transparent taxi prices, and scam-aware advice that puts you—not a middleman—first.',whatsappNumber:'94770000000',displayPhone:'+94 77 000 0000',email:'hello@clearlankatravel.com',priceRoute:'Colombo Airport → Galle',priceMin:'65',priceMax:'90',theme:'island',cardLayout:'grid',sectionOrder:['services','discover','price-guide','safety','partners'],sectionVisibility:{services:true,discover:true,'price-guide':true,safety:true,partners:true}};
let content={...defaults},items=[],currentRole=null,currentUser=null,activeType='service',recoveryMode=location.hash.includes('type=recovery')||location.search.includes('type=recovery');
const typeLabels={service:'Services',package:'Tours / Projects',hotel:'Hotels / Stays',place:'Places',partner:'Partners',guide:'Travel guides',testimonial:'Testimonials'};
function showToast(message,error=false){toast.textContent=message;toast.style.background=error?'#8b3328':'';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function setLoginStatus(message,error=false){loginStatus.textContent=message;loginStatus.style.color=error?'#a53a2f':''}
function showPasswordRecovery(){recoveryMode=true;app.hidden=true;login.hidden=false;document.querySelector('#login-title').textContent='Choose a new password';document.querySelector('#login-copy').textContent='Enter at least 8 characters for your new owner password.';document.querySelector('#admin-email-field').hidden=true;document.querySelector('#login-form [name="email"]').disabled=true;document.querySelector('#login-meta').hidden=true;const password=document.querySelector('#login-form [name="password"]');password.autocomplete='new-password';password.value='';document.querySelector('#login-submit').textContent='Update password →';setLoginStatus('')}
function openView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel===name));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#view-title').textContent=document.querySelector(`[data-view="${name}"] span`)?.textContent||'Overview';document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.view)));
document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.jump)));
document.querySelector('.nav-toggle').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.querySelector('#preview-site').addEventListener('click',()=>window.open('index.html','_blank'));
async function verifyOwner(user){const {data,error}=await client.from('site_admins').select('role').eq('id',user.id).maybeSingle();if(error||!data){await client.auth.signOut();throw new Error('This account does not have Owner Studio access.')}currentRole=data.role;currentUser=user;return data.role}
async function enterApp(user){try{await verifyOwner(user);login.hidden=true;app.hidden=false;document.querySelector('.avatar').textContent=(user.email||'OW').slice(0,2).toUpperCase();await loadCms();showToast(`Signed in as ${currentRole}`)}catch(error){setLoginStatus(error.message,true)}}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();if(!client)return setLoginStatus('Could not connect to secure login.',true);const data=new FormData(e.target);if(recoveryMode){setLoginStatus('Updating password…');const {data:result,error}=await client.auth.updateUser({password:data.get('password')});if(error)return setLoginStatus(error.message,true);recoveryMode=false;setLoginStatus('Password updated. Opening Owner Studio…');return enterApp(result.user)}setLoginStatus('Signing in…');const {data:result,error}=await client.auth.signInWithPassword({email:data.get('email'),password:data.get('password')});if(error)return setLoginStatus(error.message,true);setLoginStatus('');await enterApp(result.user)});
document.querySelector('#admin-reset').addEventListener('click',async()=>{const email=document.querySelector('#login-form [name="email"]').value;if(!email)return setLoginStatus('Enter your email first.',true);const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}${location.pathname}`});setLoginStatus(error?error.message:'Password reset email sent.',!!error)});
document.querySelector('#logout').addEventListener('click',async()=>{await client?.auth.signOut();app.hidden=true;login.hidden=false;showToast('Signed out')});
async function loadCms(){const [settingsResult,itemsResult]=await Promise.all([client.from('site_settings').select('content').eq('id','main').maybeSingle(),client.from('site_items').select('*').order('sort_order')]);if(settingsResult.error)showToast('CMS tables are not ready. Apply the production migration.',true);content={...defaults,...(settingsResult.data?.content||{})};items=itemsResult.data||[];bindContentFields();renderCatalogue();renderLayout();renderLegacyPanels();updateStats();document.querySelector('.saved-state').innerHTML='<i></i> Synced securely'}
function bindContentFields(){document.querySelectorAll('[data-field]').forEach(field=>{field.value=content[field.dataset.field]??field.value;field.oninput=()=>{content[field.dataset.field]=field.value;updatePreview()}});updatePreview()}
function updatePreview(){document.querySelector('#preview-eyebrow').textContent=(content.heroEyebrow||'').toUpperCase();document.querySelector('#preview-title').textContent=content.heroTitle||'';document.querySelector('#preview-lead').textContent=content.heroLead||''}
async function saveSettings(){const {error}=await client.from('site_settings').upsert({id:'main',content,updated_at:new Date().toISOString(),updated_by:currentUser.id});showToast(error?error.message:'Changes published to the website',!!error)}
document.querySelectorAll('.save-content').forEach(button=>button.addEventListener('click',saveSettings));
function renderCatalogue(){const panel=document.querySelector('[data-panel="services"]');panel.innerHTML=`<div class="page-title"><div><span class="overline">Editable catalogue</span><h1>Services, tours, hotels & places</h1><p>Add, edit, publish, hide, delete and reorder everything visitors can explore.</p></div><button class="primary" id="add-catalogue">＋ Add new</button></div><div class="catalog-tabs">${Object.entries(typeLabels).slice(0,4).map(([type,label])=>`<button data-catalog-type="${type}" class="${type===activeType?'active':''}">${label}</button>`).join('')}</div><div class="catalog-list card" id="catalog-list"></div>`;panel.querySelector('#add-catalogue').onclick=()=>openItemDialog(activeType);panel.querySelectorAll('[data-catalog-type]').forEach(b=>b.onclick=()=>{activeType=b.dataset.catalogType;renderCatalogue()});const rows=items.filter(i=>i.type===activeType);panel.querySelector('#catalog-list').innerHTML=rows.length?rows.map(item=>`<article class="catalog-row" data-id="${item.id}"><div class="catalog-thumb" ${item.image_url?`style="background-image:url('${escapeAttr(item.image_url)}')"`:''}>${item.image_url?'':'▧'}</div><div><small>${escapeHtml(item.location||typeLabels[item.type])}</small><b>${escapeHtml(item.title)}</b><span>${escapeHtml(item.subtitle||item.description)}</span></div><strong>${escapeHtml(item.price_label||'—')}</strong><i class="status ${item.is_published?'live':'draft'}">${item.is_published?'Published':'Hidden'}</i><div class="row-actions"><button data-edit>Edit</button><button data-delete>Delete</button></div></article>`).join(''):'<div class="empty-state">No items yet. Add your first one.</div>';panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openItemDialog(activeType,items.find(i=>i.id===b.closest('[data-id]').dataset.id)));panel.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteItem(b.closest('[data-id]').dataset.id))}
function renderLegacyPanels(){const map={guidance:'guide',partners:'partner',testimonials:'testimonial'};for(const [panelName,type] of Object.entries(map)){const panel=document.querySelector(`[data-panel="${panelName}"]`);const rows=items.filter(i=>i.type===type);panel.innerHTML=`<div class="page-title"><div><span class="overline">Editable content</span><h1>${typeLabels[type]}</h1><p>Publish and maintain this website section.</p></div><button class="primary add-section-item">＋ Add ${typeLabels[type].replace(/s$/,'')}</button></div><div class="simple-admin-grid">${rows.map(item=>`<article class="card" data-id="${item.id}"><i class="status ${item.is_published?'live':'draft'}">${item.is_published?'Published':'Hidden'}</i><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.description)}</p><button data-edit>Edit</button></article>`).join('')||'<div class="card empty-state">No items yet.</div>'}</div>`;panel.querySelector('.add-section-item').onclick=()=>openItemDialog(type);panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openItemDialog(type,items.find(i=>i.id===b.closest('[data-id]').dataset.id)))}}
function renderLayout(){const order=content.sectionOrder||defaults.sectionOrder,visibility=content.sectionVisibility||defaults.sectionVisibility;document.querySelector('#layout-editor').innerHTML=`<div class="layout-grid"><div class="card form-card"><h2>Theme & cards</h2><label>Colour theme<select id="theme-select"><option value="island">Island green</option><option value="ocean">Ocean blue</option><option value="sunset">Sunset warm</option></select></label><label>Card layout<select id="card-layout"><option value="grid">Comfortable grid</option><option value="compact">Compact grid</option><option value="list">Editorial list</option></select></label></div><div class="card"><h2>Homepage section order</h2><p class="muted">Use arrows to reorder. Hidden sections stay editable.</p><div class="section-sorter">${order.map((key,index)=>`<div data-section="${key}"><span>${key.replace('-',' ')}</span><label class="switch"><input type="checkbox" ${visibility[key]!==false?'checked':''}><i></i></label><button data-up ${index===0?'disabled':''}>↑</button><button data-down ${index===order.length-1?'disabled':''}>↓</button></div>`).join('')}</div></div></div>`;const theme=document.querySelector('#theme-select'),cards=document.querySelector('#card-layout');theme.value=content.theme||'island';cards.value=content.cardLayout||'grid';theme.onchange=()=>content.theme=theme.value;cards.onchange=()=>content.cardLayout=cards.value;document.querySelectorAll('.section-sorter>div').forEach(row=>{const key=row.dataset.section;row.querySelector('input').onchange=e=>{content.sectionVisibility={...(content.sectionVisibility||{}),[key]:e.target.checked};renderLayout()};row.querySelector('[data-up]').onclick=()=>moveSection(key,-1);row.querySelector('[data-down]').onclick=()=>moveSection(key,1)})}
function moveSection(key,delta){const order=[...(content.sectionOrder||defaults.sectionOrder)],from=order.indexOf(key),to=from+delta;if(to<0||to>=order.length)return;[order[from],order[to]]=[order[to],order[from]];content.sectionOrder=order;renderLayout()}
function updateStats(){const counts={service:0,partner:0,guide:0};items.filter(i=>i.is_published).forEach(i=>{if(i.type in counts)counts[i.type]++});const stats=document.querySelectorAll('.stats strong');if(stats[0])stats[0].textContent=counts.service;if(stats[1])stats[1].textContent=counts.partner;if(stats[2])stats[2].textContent=counts.guide}
const dialog=document.querySelector('#item-dialog'),itemForm=document.querySelector('#item-form');
function openItemDialog(type,item={}){itemForm.reset();document.querySelector('#item-dialog-title').textContent=item.id?`Edit ${typeLabels[type]}`:`Add ${typeLabels[type]}`;for(const [key,value] of Object.entries(item)){const field=itemForm.elements[key];if(field){if(field.type==='checkbox')field.checked=!!value;else field.value=value??''}}itemForm.elements.type.value=item.type||type;itemForm.elements.is_published.checked=item.id?!!item.is_published:true;dialog.showModal()}
itemForm.addEventListener('submit',async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){dialog.close();return}const fd=new FormData(itemForm),id=fd.get('id');const row={type:fd.get('type'),title:fd.get('title').trim(),subtitle:fd.get('subtitle').trim(),description:fd.get('description').trim(),price_label:fd.get('price_label').trim(),location:fd.get('location').trim(),badge:fd.get('badge').trim(),image_url:fd.get('image_url').trim(),image_alt:fd.get('image_alt').trim(),sort_order:Number(fd.get('sort_order')||0),is_published:fd.get('is_published')==='on',updated_at:new Date().toISOString(),updated_by:currentUser.id};const result=id?await client.from('site_items').update(row).eq('id',id):await client.from('site_items').insert(row);if(result.error)return showToast(result.error.message,true);dialog.close();await loadCms();showToast('Catalogue item published')});
async function deleteItem(id){if(!confirm('Delete this item permanently?'))return;const {error}=await client.from('site_items').delete().eq('id',id);if(error)return showToast(error.message,true);await loadCms();showToast('Item deleted')}
document.querySelector('#upload-demo').onclick=()=>{const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif';input.onchange=()=>uploadImage(input.files[0]);input.click()};
async function uploadImage(file){if(!file)return;const safe=file.name.toLowerCase().replace(/[^a-z0-9.]+/g,'-'),path=`${currentUser.id}/${Date.now()}-${safe}`;showToast('Uploading image…');const {error}=await client.storage.from('site-media').upload(path,file,{upsert:false});if(error)return showToast(error.message,true);const {data}=client.storage.from('site-media').getPublicUrl(path);await navigator.clipboard?.writeText(data.publicUrl);showToast('Image uploaded; URL copied')}
document.querySelector('#media-preview').onclick=()=>showToast('Paste an uploaded image URL into any catalogue item.');
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(value=''){return escapeHtml(value).replace(/`/g,'&#96;')}
if(client){client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')return showPasswordRecovery();if(session?.user&&app.hidden&&!recoveryMode)enterApp(session.user);if(!session){app.hidden=true;login.hidden=false}});client.auth.getSession().then(({data})=>{if(recoveryMode)return showPasswordRecovery();if(data.session?.user)enterApp(data.session.user)})}else setLoginStatus('Could not load secure login. Check your internet connection.',true);
